package sport;
// Generated Oct 30, 2016 7:15:16 PM by Hibernate Tools 4.3.1



/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer cid;
     private String cfname;
     private String clname;
     private String caddress;
     private String ctel;
     private String cemail;

    public Customer() {
    }

    public Customer(String cfname, String clname, String caddress, String ctel, String cemail) {
       this.cfname = cfname;
       this.clname = clname;
       this.caddress = caddress;
       this.ctel = ctel;
       this.cemail = cemail;
    }
   
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }
    public String getCfname() {
        return this.cfname;
    }
    
    public void setCfname(String cfname) {
        this.cfname = cfname;
    }
    public String getClname() {
        return this.clname;
    }
    
    public void setClname(String clname) {
        this.clname = clname;
    }
    public String getCaddress() {
        return this.caddress;
    }
    
    public void setCaddress(String caddress) {
        this.caddress = caddress;
    }
    public String getCtel() {
        return this.ctel;
    }
    
    public void setCtel(String ctel) {
        this.ctel = ctel;
    }
    public String getCemail() {
        return this.cemail;
    }
    
    public void setCemail(String cemail) {
        this.cemail = cemail;
    }

}


